### ISSUE TITLE
ProductColReplication broken

### ISSUE THREAD

**Issue by Kosmos42** [statistics101/product2#26]
Было:

![lrv_productcol_ss_lag2_17_57](https://user-images.githubusercontent.com/18413549/32018690-8187d1a4-b9ec-11e7-890c-483f0809bb6c.jpg)
![lrv_productcol_ss_lag3_17_57](https://user-images.githubusercontent.com/18413549/32018691-81b154b6-b9ec-11e7-8cee-003256aec45c.jpg)
now
![lrv_productcol_ss_lag2_23_02](https://user-images.githubusercontent.com/18413549/32018713-8facfba6-b9ec-11e7-9f1d-65dd4cef197c.jpg)
![lrv_productcol_ss_lag3_23_02](https://user-images.githubusercontent.com/18413549/32018714-8fd6f46a-b9ec-11e7-84f0-45fd6fd9d926.jpg)
![lrv_productcol_ss_lag1_23_02](https://user-images.githubusercontent.com/18413549/32018715-8fff548c-b9ec-11e7-9033-cecf7765ec85.jpg)

**Comment by statistics101** [comment]
Broke after Lesha did something.

**Comment by statistics101** [comment]
Download the old version. When it was not broken.

**Comment by statistics101** [comment]
23 October it was OK. 25 October this bug was posted.

**Comment by statistics101** [comment]
1. Lesha reproduced the picture at the top of this stack using the code of 23 October.
2. Tried to compare the old code to our new one. The differences are:

**Comment by statistics101** [comment]
Commented the experimental  code about NA's. In CreateLRVof2dArray


  # Commented out at Nov. 3
  # supposed that was the reason we have
  # productColReplicated pictures broken
  # (shifted down, instead of being
  # equally distributed around the horyzontal line)
  # rowMeansArray <- rowMeans(array2d, na.rm = T)
  # lrv <- sqrt(dim(array2d)[1]) * var(rowMeansArray)
}
